//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using dataShow.Models;
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web.Mvc;

public partial class DataShowEntities : DbContext
{
    public DataShowEntities()
        : base("name=DataShowEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<MAC> MAC { get; set; }
    public virtual DbSet<rawData> rawData { get; set; }
    public virtual DbSet<SOURCE> SOURCE { get; set; }
    public virtual DbSet<SourceDetail> SourceDetail { get; set; }
    public virtual DbSet<TIMES> TIMES { get; set; }
    public virtual DbSet<User> User { get; set; }

   
}
