//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataShow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rawData
    {
        public string rawMac { get; set; }
        public int rawSource { get; set; }
        public System.DateTime rawTime { get; set; }
        public bool macOp { get; set; }
        public bool sourceOp { get; set; }
        public bool timeOp { get; set; }
        public int rawID { get; set; }
    }
}
