//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataShow.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SOURCE", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SOURCE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int sourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string macAddressField;
        
        private int stayTimeField;
        
        private short numField;
        
        private System.DateTime datatimeField;
        
        private int idField;
        
        private System.DateTime newtimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sourceID {
            get {
                return this.sourceIDField;
            }
            set {
                if ((this.sourceIDField.Equals(value) != true)) {
                    this.sourceIDField = value;
                    this.RaisePropertyChanged("sourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string macAddress {
            get {
                return this.macAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.macAddressField, value) != true)) {
                    this.macAddressField = value;
                    this.RaisePropertyChanged("macAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int stayTime {
            get {
                return this.stayTimeField;
            }
            set {
                if ((this.stayTimeField.Equals(value) != true)) {
                    this.stayTimeField = value;
                    this.RaisePropertyChanged("stayTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public short num {
            get {
                return this.numField;
            }
            set {
                if ((this.numField.Equals(value) != true)) {
                    this.numField = value;
                    this.RaisePropertyChanged("num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime datatime {
            get {
                return this.datatimeField;
            }
            set {
                if ((this.datatimeField.Equals(value) != true)) {
                    this.datatimeField = value;
                    this.RaisePropertyChanged("datatime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime newtime {
            get {
                return this.newtimeField;
            }
            set {
                if ((this.newtimeField.Equals(value) != true)) {
                    this.newtimeField = value;
                    this.RaisePropertyChanged("newtime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SourceDetail", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SourceDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int sourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sourceLocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sourceID {
            get {
                return this.sourceIDField;
            }
            set {
                if ((this.sourceIDField.Equals(value) != true)) {
                    this.sourceIDField = value;
                    this.RaisePropertyChanged("sourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sourceLocation {
            get {
                return this.sourceLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.sourceLocationField, value) != true)) {
                    this.sourceLocationField = value;
                    this.RaisePropertyChanged("sourceLocation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIMES", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TIMES : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int periodTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string macAddressField;
        
        private int sourceIDField;
        
        private short numField;
        
        private int timeIDField;
        
        private System.DateTime datatimeField;
        
        private System.DateTime newtimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int periodTime {
            get {
                return this.periodTimeField;
            }
            set {
                if ((this.periodTimeField.Equals(value) != true)) {
                    this.periodTimeField = value;
                    this.RaisePropertyChanged("periodTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string macAddress {
            get {
                return this.macAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.macAddressField, value) != true)) {
                    this.macAddressField = value;
                    this.RaisePropertyChanged("macAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int sourceID {
            get {
                return this.sourceIDField;
            }
            set {
                if ((this.sourceIDField.Equals(value) != true)) {
                    this.sourceIDField = value;
                    this.RaisePropertyChanged("sourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public short num {
            get {
                return this.numField;
            }
            set {
                if ((this.numField.Equals(value) != true)) {
                    this.numField = value;
                    this.RaisePropertyChanged("num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int timeID {
            get {
                return this.timeIDField;
            }
            set {
                if ((this.timeIDField.Equals(value) != true)) {
                    this.timeIDField = value;
                    this.RaisePropertyChanged("timeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime datatime {
            get {
                return this.datatimeField;
            }
            set {
                if ((this.datatimeField.Equals(value) != true)) {
                    this.datatimeField = value;
                    this.RaisePropertyChanged("datatime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime newtime {
            get {
                return this.newtimeField;
            }
            set {
                if ((this.newtimeField.Equals(value) != true)) {
                    this.newtimeField = value;
                    this.RaisePropertyChanged("newtime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MAC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MAC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime datatimeField;
        
        private int sourceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string macaddressField;
        
        private int macIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime datatime {
            get {
                return this.datatimeField;
            }
            set {
                if ((this.datatimeField.Equals(value) != true)) {
                    this.datatimeField = value;
                    this.RaisePropertyChanged("datatime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int sourceID {
            get {
                return this.sourceIDField;
            }
            set {
                if ((this.sourceIDField.Equals(value) != true)) {
                    this.sourceIDField = value;
                    this.RaisePropertyChanged("sourceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string macaddress {
            get {
                return this.macaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.macaddressField, value) != true)) {
                    this.macaddressField = value;
                    this.RaisePropertyChanged("macaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int macID {
            get {
                return this.macIDField;
            }
            set {
                if ((this.macIDField.Equals(value) != true)) {
                    this.macIDField = value;
                    this.RaisePropertyChanged("macID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        dataShow.ServiceReference.HelloWorldResponse HelloWorld(dataShow.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<dataShow.ServiceReference.HelloWorldResponse> HelloWorldAsync(dataShow.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetSourceResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSource", ReplyAction="*")]
        dataShow.ServiceReference.GetSourceResponse GetSource(dataShow.ServiceReference.GetSourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSource", ReplyAction="*")]
        System.Threading.Tasks.Task<dataShow.ServiceReference.GetSourceResponse> GetSourceAsync(dataShow.ServiceReference.GetSourceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetSourceDetailResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSourceDetail", ReplyAction="*")]
        dataShow.ServiceReference.GetSourceDetailResponse GetSourceDetail(dataShow.ServiceReference.GetSourceDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSourceDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<dataShow.ServiceReference.GetSourceDetailResponse> GetSourceDetailAsync(dataShow.ServiceReference.GetSourceDetailRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetTimesResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTimes", ReplyAction="*")]
        dataShow.ServiceReference.GetTimesResponse GetTimes(dataShow.ServiceReference.GetTimesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTimes", ReplyAction="*")]
        System.Threading.Tasks.Task<dataShow.ServiceReference.GetTimesResponse> GetTimesAsync(dataShow.ServiceReference.GetTimesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetMacResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMac", ReplyAction="*")]
        dataShow.ServiceReference.GetMacResponse GetMac(dataShow.ServiceReference.GetMacRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMac", ReplyAction="*")]
        System.Threading.Tasks.Task<dataShow.ServiceReference.GetMacResponse> GetMacAsync(dataShow.ServiceReference.GetMacRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public dataShow.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(dataShow.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public dataShow.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(dataShow.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSourceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSource", Namespace="http://tempuri.org/", Order=0)]
        public dataShow.ServiceReference.GetSourceRequestBody Body;
        
        public GetSourceRequest() {
        }
        
        public GetSourceRequest(dataShow.ServiceReference.GetSourceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSourceRequestBody {
        
        public GetSourceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSourceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSourceResponse", Namespace="http://tempuri.org/", Order=0)]
        public dataShow.ServiceReference.GetSourceResponseBody Body;
        
        public GetSourceResponse() {
        }
        
        public GetSourceResponse(dataShow.ServiceReference.GetSourceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSourceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public dataShow.ServiceReference.SOURCE[] GetSourceResult;
        
        public GetSourceResponseBody() {
        }
        
        public GetSourceResponseBody(dataShow.ServiceReference.SOURCE[] GetSourceResult) {
            this.GetSourceResult = GetSourceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSourceDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSourceDetail", Namespace="http://tempuri.org/", Order=0)]
        public dataShow.ServiceReference.GetSourceDetailRequestBody Body;
        
        public GetSourceDetailRequest() {
        }
        
        public GetSourceDetailRequest(dataShow.ServiceReference.GetSourceDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSourceDetailRequestBody {
        
        public GetSourceDetailRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSourceDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSourceDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public dataShow.ServiceReference.GetSourceDetailResponseBody Body;
        
        public GetSourceDetailResponse() {
        }
        
        public GetSourceDetailResponse(dataShow.ServiceReference.GetSourceDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSourceDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public dataShow.ServiceReference.SourceDetail[] GetSourceDetailResult;
        
        public GetSourceDetailResponseBody() {
        }
        
        public GetSourceDetailResponseBody(dataShow.ServiceReference.SourceDetail[] GetSourceDetailResult) {
            this.GetSourceDetailResult = GetSourceDetailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTimesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTimes", Namespace="http://tempuri.org/", Order=0)]
        public dataShow.ServiceReference.GetTimesRequestBody Body;
        
        public GetTimesRequest() {
        }
        
        public GetTimesRequest(dataShow.ServiceReference.GetTimesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTimesRequestBody {
        
        public GetTimesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTimesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTimesResponse", Namespace="http://tempuri.org/", Order=0)]
        public dataShow.ServiceReference.GetTimesResponseBody Body;
        
        public GetTimesResponse() {
        }
        
        public GetTimesResponse(dataShow.ServiceReference.GetTimesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTimesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public dataShow.ServiceReference.TIMES[] GetTimesResult;
        
        public GetTimesResponseBody() {
        }
        
        public GetTimesResponseBody(dataShow.ServiceReference.TIMES[] GetTimesResult) {
            this.GetTimesResult = GetTimesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMacRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMac", Namespace="http://tempuri.org/", Order=0)]
        public dataShow.ServiceReference.GetMacRequestBody Body;
        
        public GetMacRequest() {
        }
        
        public GetMacRequest(dataShow.ServiceReference.GetMacRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMacRequestBody {
        
        public GetMacRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMacResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMacResponse", Namespace="http://tempuri.org/", Order=0)]
        public dataShow.ServiceReference.GetMacResponseBody Body;
        
        public GetMacResponse() {
        }
        
        public GetMacResponse(dataShow.ServiceReference.GetMacResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMacResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public dataShow.ServiceReference.MAC[] GetMacResult;
        
        public GetMacResponseBody() {
        }
        
        public GetMacResponseBody(dataShow.ServiceReference.MAC[] GetMacResult) {
            this.GetMacResult = GetMacResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : dataShow.ServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<dataShow.ServiceReference.WebService1Soap>, dataShow.ServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dataShow.ServiceReference.HelloWorldResponse dataShow.ServiceReference.WebService1Soap.HelloWorld(dataShow.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            dataShow.ServiceReference.HelloWorldRequest inValue = new dataShow.ServiceReference.HelloWorldRequest();
            inValue.Body = new dataShow.ServiceReference.HelloWorldRequestBody();
            dataShow.ServiceReference.HelloWorldResponse retVal = ((dataShow.ServiceReference.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dataShow.ServiceReference.HelloWorldResponse> dataShow.ServiceReference.WebService1Soap.HelloWorldAsync(dataShow.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<dataShow.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            dataShow.ServiceReference.HelloWorldRequest inValue = new dataShow.ServiceReference.HelloWorldRequest();
            inValue.Body = new dataShow.ServiceReference.HelloWorldRequestBody();
            return ((dataShow.ServiceReference.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dataShow.ServiceReference.GetSourceResponse dataShow.ServiceReference.WebService1Soap.GetSource(dataShow.ServiceReference.GetSourceRequest request) {
            return base.Channel.GetSource(request);
        }
        
        public dataShow.ServiceReference.SOURCE[] GetSource() {
            dataShow.ServiceReference.GetSourceRequest inValue = new dataShow.ServiceReference.GetSourceRequest();
            inValue.Body = new dataShow.ServiceReference.GetSourceRequestBody();
            dataShow.ServiceReference.GetSourceResponse retVal = ((dataShow.ServiceReference.WebService1Soap)(this)).GetSource(inValue);
            return retVal.Body.GetSourceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dataShow.ServiceReference.GetSourceResponse> dataShow.ServiceReference.WebService1Soap.GetSourceAsync(dataShow.ServiceReference.GetSourceRequest request) {
            return base.Channel.GetSourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<dataShow.ServiceReference.GetSourceResponse> GetSourceAsync() {
            dataShow.ServiceReference.GetSourceRequest inValue = new dataShow.ServiceReference.GetSourceRequest();
            inValue.Body = new dataShow.ServiceReference.GetSourceRequestBody();
            return ((dataShow.ServiceReference.WebService1Soap)(this)).GetSourceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dataShow.ServiceReference.GetSourceDetailResponse dataShow.ServiceReference.WebService1Soap.GetSourceDetail(dataShow.ServiceReference.GetSourceDetailRequest request) {
            return base.Channel.GetSourceDetail(request);
        }
        
        public dataShow.ServiceReference.SourceDetail[] GetSourceDetail() {
            dataShow.ServiceReference.GetSourceDetailRequest inValue = new dataShow.ServiceReference.GetSourceDetailRequest();
            inValue.Body = new dataShow.ServiceReference.GetSourceDetailRequestBody();
            dataShow.ServiceReference.GetSourceDetailResponse retVal = ((dataShow.ServiceReference.WebService1Soap)(this)).GetSourceDetail(inValue);
            return retVal.Body.GetSourceDetailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dataShow.ServiceReference.GetSourceDetailResponse> dataShow.ServiceReference.WebService1Soap.GetSourceDetailAsync(dataShow.ServiceReference.GetSourceDetailRequest request) {
            return base.Channel.GetSourceDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<dataShow.ServiceReference.GetSourceDetailResponse> GetSourceDetailAsync() {
            dataShow.ServiceReference.GetSourceDetailRequest inValue = new dataShow.ServiceReference.GetSourceDetailRequest();
            inValue.Body = new dataShow.ServiceReference.GetSourceDetailRequestBody();
            return ((dataShow.ServiceReference.WebService1Soap)(this)).GetSourceDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dataShow.ServiceReference.GetTimesResponse dataShow.ServiceReference.WebService1Soap.GetTimes(dataShow.ServiceReference.GetTimesRequest request) {
            return base.Channel.GetTimes(request);
        }
        
        public dataShow.ServiceReference.TIMES[] GetTimes() {
            dataShow.ServiceReference.GetTimesRequest inValue = new dataShow.ServiceReference.GetTimesRequest();
            inValue.Body = new dataShow.ServiceReference.GetTimesRequestBody();
            dataShow.ServiceReference.GetTimesResponse retVal = ((dataShow.ServiceReference.WebService1Soap)(this)).GetTimes(inValue);
            return retVal.Body.GetTimesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dataShow.ServiceReference.GetTimesResponse> dataShow.ServiceReference.WebService1Soap.GetTimesAsync(dataShow.ServiceReference.GetTimesRequest request) {
            return base.Channel.GetTimesAsync(request);
        }
        
        public System.Threading.Tasks.Task<dataShow.ServiceReference.GetTimesResponse> GetTimesAsync() {
            dataShow.ServiceReference.GetTimesRequest inValue = new dataShow.ServiceReference.GetTimesRequest();
            inValue.Body = new dataShow.ServiceReference.GetTimesRequestBody();
            return ((dataShow.ServiceReference.WebService1Soap)(this)).GetTimesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        dataShow.ServiceReference.GetMacResponse dataShow.ServiceReference.WebService1Soap.GetMac(dataShow.ServiceReference.GetMacRequest request) {
            return base.Channel.GetMac(request);
        }
        
        public dataShow.ServiceReference.MAC[] GetMac() {
            dataShow.ServiceReference.GetMacRequest inValue = new dataShow.ServiceReference.GetMacRequest();
            inValue.Body = new dataShow.ServiceReference.GetMacRequestBody();
            dataShow.ServiceReference.GetMacResponse retVal = ((dataShow.ServiceReference.WebService1Soap)(this)).GetMac(inValue);
            return retVal.Body.GetMacResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<dataShow.ServiceReference.GetMacResponse> dataShow.ServiceReference.WebService1Soap.GetMacAsync(dataShow.ServiceReference.GetMacRequest request) {
            return base.Channel.GetMacAsync(request);
        }
        
        public System.Threading.Tasks.Task<dataShow.ServiceReference.GetMacResponse> GetMacAsync() {
            dataShow.ServiceReference.GetMacRequest inValue = new dataShow.ServiceReference.GetMacRequest();
            inValue.Body = new dataShow.ServiceReference.GetMacRequestBody();
            return ((dataShow.ServiceReference.WebService1Soap)(this)).GetMacAsync(inValue);
        }
    }
}
