//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMES
    {
        public int periodTime { get; set; }
        public string macAddress { get; set; }
        public int sourceID { get; set; }
        public short num { get; set; }
        public int timeID { get; set; }
        public System.DateTime datatime { get; set; }
        public System.DateTime newtime { get; set; }
    }
}
